### ISSUE TITLE
change unit to meter

### ISSUE THREAD

**Issue by mardani78** [NieuwlandGeo/SLDReader#152] opened 2023-04-24 08:05 UTC
hi,
I wanna change my SLD unit from pixel to meter, but it seems that my SLDREADER doesn't support *uom="http://www.opengeospatial.org/se/units/metre*
(which I have downloaded the last version recently)
which SLDREADER version supports both *uom="http://www.opengeospatial.org/se/units/metre* and *INITIAL GAP* ?

thank you.

**Comment by ajkopinga** [comment] 2023-04-25 07:44
SLDReader currently only supports pixels as unit of measure. It will take quite a bit of work to get this implemented correctly.

I'll close this issue, since it is a duplicate of #36. You can subscribe to that issue to be notified when uoms are supported.

**Closed as completed by ajkopinga** 2023-04-25 07:44 UTC
